name: Test the DCE composite action

on:
    push:
      branches:
        - main
    pull_request:
    workflow_dispatch:

jobs:
    permission_check:
        runs-on: ubuntu-latest
        outputs:
          can-write: ${{ steps.check.outputs.can-write }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        steps:
        - id: check
          run: |
            # If the AWS_ACCESS_KEY_ID secret is MIA we can't run tests
            if [[ -z "$AWS_ACCESS_KEY_ID" ]]; then
                echo "can-write=false" >> $GITHUB_OUTPUT
            else
                echo "can-write=true" >> $GITHUB_OUTPUT
            fi

    test-action:
      runs-on: ubuntu-latest
      needs: [permission_check]
      if: needs.permission_check.outputs.can-write == 'true'
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Run DCE Environment Setup and Login
          id: dce_setup
          uses: ./
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            budget-amount: '10'
            budget-currency: 'USD'
            expiry: '10m'
            email: 'colin.hutchinson+gha@observeinc.com'

        - name: Setup AWS credentials (DCE)
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ steps.dce_setup.outputs.dce-access-key-id }}
            aws-secret-access-key: ${{ steps.dce_setup.outputs.dce-secret-access-key }}
            aws-session-token: ${{ steps.dce_setup.outputs.dce-session-token }}
            aws-region: us-west-1

        - name: AWS Identity (DCE)
          run: aws sts get-caller-identity
